### ISSUE TITLE
Mark not all strawberries as progression if not required

### ISSUE THREAD

**Issue by dafatman922** [doshyw/CelesteArchipelago#24]
As noted in other implementations of AP, some issues can come about if ALL of the items are progression (example: exclude_locations simply does not work in a solo world, because there's no items that can go in those locations). As well, there are gameflow issues that come with having a lot of a specific item being progression, but only a relatively small amount of it being required, resulting in games that end really fast, or even in sphere 1.

There are two options I've seen to resolve the second problem, one of which also solves the first problem.

Option A. Mark some or all berries so that they skip balancing. That way, when the game does progression balancing, it doesn't push your berries early (this might already be implemented and I don't know, if it is then let me know)

Option B. Mark only a set of the berries as Progression, and mark the rest as Useful. This is what e.g. Sonic Adventure 2 does, and it seems like a good idea.

Of course, if you have an idea for a filler item as well, that'd also be good to have, and it might be a good idea to have some berries in the pool be replaced by these filler items. However as it currently stands, I think doing at least one of the two above is a good idea

**Comment by doshyw** [comment]
Fixed with https://github.com/doshyw/CelesteArchipelago/pull/31 and https://github.com/doshyw/Archipelago/pull/2
