### ISSUE TITLE
C-Sides check for received Completions instead of Crystal hearts

### ISSUE THREAD

**Issue by MageoMage** [doshyw/CelesteArchipelago#39]
Been looking a little through the logic files of the apworld and if I am not mistaken in progression.py it states this: (lines 95 onward in the Alpha 0.3.0 release)
```
        elif side == CelesteSide.C_SIDE:
            return lambda state: state.has_all(
                {
                    BaseData.item_name(CelesteItemType.COMPLETION, level, CelesteSide.A_SIDE),
                    BaseData.item_name(CelesteItemType.COMPLETION, level, CelesteSide.B_SIDE),
                },
                player,
            )
```
Which if I am reading that correctly means that C-Sides unlock requirements currently are being sent the completion for the A and B side instead of The Crystal Hearts for those as it is stated in [en_Celeste.md](https://github.com/doshyw/Archipelago/blob/885c19d470477445df5fb2ff3c23c098f4a1da3d/worlds/celeste/docs/en_Celeste.md) and how it actually works in the mod iirc.

**Comment by doshyw** [comment]
Fixed in https://github.com/doshyw/Archipelago/pull/6.
